#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

# Delete existing rules
echo "y" | sudo ufw reset

# Establish firewall rules
ufw limit ssh
ufw allow http
ufw allow https
ufw allow from 10.0.0.0/8
ufw allow from 172.16.0.0/12
ufw allow from 192.168.0.0/16
ufw default deny incoming || true

# Enable ufw
echo "ufw --force enable" >> /etc/rc.local
# Ensure that /etc/rc.local is executable
chmod +x /etc/rc.local
