#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

if [[ $DIB_RELEASE = 7* ]]; then
    yum-config-manager --enable PowerTools
elif [[ $DIB_RELEASE = 8* ]]; then
    $YUM config-manager --set-enabled powertools
else
    echo "Unknown centos release name: '$DIB_RELEASE'"
    exit 1
fi

