#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail


if [[ $DIB_RELEASE = 7* ]]; then
    yum remove -y chrony
    yum install -y ntp
    echo "server ntp.tacc.utexas.edu iburst" >> /etc/ntp.conf
    systemctl enable ntpd
elif [[ $DIB_RELEASE = 8* ]]; then
    echo "server ntp.tacc.utexas.edu iburst" >> /etc/chrony.conf
    systemctl enable chronyd
else
    echo "Unknown centos release name: '$DIB_RELEASE'"
    exit 1
fi
