#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

git clone -b centos8 https://github.com/ChameleonCloud/g5k-checks.git

gem --version
gem install popen4 -v '0.1.2'
gem install unf_ext -v '0.0.7.1'
gem install rest-client -v '2.1.0'
gem install mixlib-cli -v '1.5.0'
gem install mixlib-config -v '2.2.1'
gem install mixlib-log -v '1.6.0'
gem install mixlib-shellout -v '2.2.6'
# skip dependency checks when installing ohai.
# chef-utils requires Ruby version >= 2.6.0. 
# centos has ruby version of 2.5.0
gem install ohai -f -v '<7'
gem install rspec -v '2.14.1'
#ln -sf /root/.rbenv/shims/gem /bin/gem
#ln -sf /root/.rbenv/shims/ruby /bin/ruby

pushd g5k-checks
sudo ./scripts/build_rpm.sh
sudo $YUM localinstall -y /root/rpmbuild/RPMS/noarch/rubygem-g5k-checks-0.7.5-1.el$DIB_RELEASE.noarch.rpm
popd

ln -s /usr/bin/g5k-checks /usr/bin/cc-checks

cat > /etc/g5k-checks.conf <<'EOF'
# This is a yaml file for G5kchecks configuration
---
# list of check enabled;
# testlist:
#  - mem
#  - bios
testlist:
  - all

# directory destination of g5kchecks output file in failure case
output_dir: /var/lib/g5kchecks/

# list of check removed
removetestlist:
  - bmc
  - clk
  - mountpoint
  - part
  - testdisk
  - os

# check if directory bellow are mounted
#mountpoint:
#  - /export/home
#  - /dev/sda5

# type of input description (retrieve json from rest or file)
retrieve_from: rest

# in case of rest, should provide an url
retrieve_url: https://api.chameleoncloud.org

# specify a branch at the end of uri (syntax will be: ?branch=mybranch at the
# end of uri)
#branch: mybranch

# Add another branch if the first url doesn't work
fallback_branch: testing

# in case of file, should provide a directory
#retrieve_dir: /tmp/
EOF
