#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

pip3 install --upgrade pip

pip3 install \
  python-cinderclient \
  python-glanceclient \
  python-heatclient \
  python-keystoneclient \
  python-neutronclient \
  python-novaclient \
  python-openstackclient \
  oslo.log \
  python-swiftclient \
  gnocchiclient \
  ansible \
  libvirt-python \
  --ignore-installed PyYAML
