#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

if [[ $DIB_RELEASE = 7* ]]; then
    sed -i 's%\(initrd\|linux\)efi /boot%\1 /boot%g' /boot/grub2/grub.cfg
fi
