#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -o errexit
set -o nounset
set -o pipefail

#############################################################
# Pre-Installation
#############################################################

MPICH_TMP_FOLDER=/root/tmp
mkdir -p $MPICH_TMP_FOLDER

# facter is used for hostfile generation in complex appliances
yum install facter

#############################################################
# Installation
#############################################################

cd $MPICH_TMP_FOLDER

# Get MPICH
VER=4.2.1
wget -nv https://www.mpich.org/static/downloads/${VER}/mpich-${VER}.tar.gz
tar xvfz mpich-${VER}.tar.gz && cd mpich-${VER}

# build and install MPICH
./configure
make -j
make install

# install cpi example
cd examples
mpicc -o /usr/local/bin/cpi cpi.c

#############################################################
# Cleaning
#############################################################

# Clean the tmp folder
rm -rf $MPICH_TMP_FOLDER

exit 0
