#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -x
set -o pipefail

# Disable NOUVEAU http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#runfile-nouveau
cat > '/etc/modprobe.d/blacklist-nouveau.conf' <<- EOM
blacklist nouveau
options nouveau modeset=0
EOM

dracut --force

exit 0
